-- Tabela de Despesas
create table if not exists public.expenses (
    id bigint generated by default as identity primary key,
    description text not null,
    amount numeric(10, 2) not null,
    category text not null,
    date date not null default current_date,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS (Row Level Security)
alter table public.expenses enable row level security;

-- Política de acesso (Permitir tudo para autenticados por enquanto, ou ajustar conforme necessidade)
create policy "Enable all access for authenticated users" on public.expenses
    for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- Se não estiver usando autenticação no frontend ainda (apenas anon), pode ser necessário:
-- create policy "Enable read access for all users" on public.expenses for select using (true);
-- create policy "Enable insert access for all users" on public.expenses for insert with check (true);
